module Forms
  class InvalidMementoError < RuntimeError
    def initialize(memento)
      super "Invalid form memento. Expecting format of '<model_name>:<page_url>'. Received value: <#{memento}>"
    end
  end
  
  class Simple < ActiveRecord::Base
    set_table_name "forms"
    
    # Creates a SimpleForm from the attributes generated by using the <r:form /> tag.
    def initialize(attributes = {})
      memento = attributes.delete(:form_memento)
      raise InvalidMementoError.new(memento) unless memento =~ /^(\w*?):(.*)$/
      
      model_name, page_url = $1, $2
      form_attributes = attributes[model_name] || {}
      form_attributes.update(:model_name => model_name, :page_url => page_url)
      super(form_attributes)
    end
  end
end