# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 6) do

  create_table "authors", :force => true do |t|
    t.column "login",                     :string
    t.column "email",                     :string
    t.column "crypted_password",          :string,   :limit => 40
    t.column "salt",                      :string,   :limit => 40
    t.column "created_at",                :datetime
    t.column "updated_at",                :datetime
    t.column "remember_token",            :string
    t.column "remember_token_expires_at", :datetime
    t.column "first_name",                :string
    t.column "last_name",                 :string
    t.column "website",                   :string
    t.column "notes",                     :text
  end

  create_table "extensions", :force => true do |t|
    t.column "name",        :string
    t.column "description", :text
    t.column "website_url", :string
    t.column "code_url",    :string
    t.column "created_at",  :datetime
    t.column "updated_at",  :datetime
    t.column "author_id",   :integer
  end

end
