#
# This is only an example configuration. Please see the Rails
# documentation for more details.
#

development:
  adapter: postgresql
  database: psrc_dev

staging:
  adapter: postgresql
  database: psrc_draft
  
test:
  adapter: postgresql
  database: psrc_test

production:
  adapter: postgresql
  database: psrc_prod
