# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 8) do

# Could not dump table "config" because of following NameError
#   uninitialized constant StringIO

# Could not dump table "layouts" because of following NameError
#   uninitialized constant ActiveRecord::StringIO

# Could not dump table "page_parts" because of following NameError
#   uninitialized constant ActiveRecord::StringIO

# Could not dump table "pages" because of following NameError
#   uninitialized constant ActiveRecord::StringIO

# Could not dump table "snippets" because of following NameError
#   uninitialized constant ActiveRecord::StringIO

# Could not dump table "users" because of following NameError
#   uninitialized constant ActiveRecord::StringIO

end
