#
# This is only an example configuration. Please see the Rails
# documentation for more details.
#

development:
  adapter: sqlite3
  database: db/radiant_dev.sqlite.db
  username: root
  password:
  host: localhost
  
test:
  adapter: sqlite3
  database: db/radiant_test.sqlite.db
  username: root
  password:
  host: localhost

production:
  adapter: sqlite3
  database: db/radiant_live.sqlite.db
  username: root
  password:
  host: localhost